### ISSUE TITLE
git / gitHub tutorial

### ISSUE THREAD

**Issue by PythonCHB** [UWPCE-PythonCert/IntroToPython-2014#107]
We need an updated git/gitHub tutorial -- only the stuff they need for the class

We'll go through the whole work flow in class.
- we create the class gutHub account
- the students each fork the repo
- they create a directory for their work
- they put some stuff in it
- they do a pull request with their stuff
- we review and accept the pull requests.

**Comment by PythonCHB** [comment]
Here is a nice-looking git intro:

http://rogerdudler.github.io/git-guide/

**Comment by codedragon** [comment]
This is very cool too:

https://try.github.io/levels/1/challenges/1

On Wed, Sep 23, 2015 at 3:26 PM, Christopher H.Barker, PhD <
notifications@github.com> wrote:

> Here is a nice-looking git intro:
> 
> http://rogerdudler.github.io/git-guide/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/UWPCE-PythonCert/IntroToPython/issues/107#issuecomment-142748181
> .

## 

Maria Mckinley
Software Developer with Bonus SysAdmin Experience
www.mariakathryn.net
www.linkedin.com/in/mariamckinley

_NOTICE:_ Due to Presidential Executive Orders still not rescinded by
President Obama, the National Security Agency may have read this email
without warning, warrant, or notice, and certainly without probable cause.
They may do this without any judicial or legislative oversight. Click here
to learn more about current US laws and your rights
http://www.aclu.org/national-security/surveillance-privacy.

**Comment by cewing** [comment]
If any of the students want to move on from basic git stuff, or gain a much more solid conceptual grasp of what git branches, HEAD and so on all mean, this is a fantastic tutorial along the same lines: http://pcottle.github.io/learnGitBranching/

**Comment by PythonCHB** [comment]
Cool - we've got some good references.

Now we need the in-class tutorial updated... -- Session 2.

**Comment by codedragon** [comment]
I have most of Monday set aside to work on it, but don't think I'll get
much done on it this weekend. I'll try to work on it during nap time. My
naps are generally shorter than his. :)

~m

On Fri, Oct 9, 2015 at 9:01 PM, Christopher H.Barker, PhD <
notifications@github.com> wrote:

> Cool - we've got some good references.
> 
> Now we need the in-class tutorial updated... -- Session 2.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/UWPCE-PythonCert/IntroToPython/issues/107#issuecomment-147031465
> .

## 

Maria Mckinley
Software Developer with Bonus SysAdmin Experience
www.mariakathryn.net
www.linkedin.com/in/mariamckinley

_NOTICE:_ Due to Presidential Executive Orders still not rescinded by
President Obama, the National Security Agency may have read this email
without warning, warrant, or notice, and certainly without probable cause.
They may do this without any judicial or legislative oversight. Click here
to learn more about current US laws and your rights
http://www.aclu.org/national-security/surveillance-privacy.
