### ISSUE TITLE
Move Solutions to ???

### ISSUE THREAD

**Issue by PythonCHB** [UWPCE-PythonCert/IntroToPython-2014#132]
We need to put the Solutions somewhere we can find them, but it won't be obvious to Studetns where there are :-)

**Comment by PythonCHB** [comment]
I've moved all the solutions to their own branch. Kind of a miss-use of branches, but what the heck.

And savvy git-using students will be abel to find them, but what the heck -- give them credit for ingenuity!

**Comment by codedragon** [comment]
lol, god enough.

On Mon, Oct 5, 2015 at 9:27 PM, Christopher H.Barker, PhD <
notifications@github.com> wrote:

> I've moved all the solutions to their own branch. Kind of a miss-use of
> branches, but what the heck.
> 
> And savvy git-using students will be abel to find them, but what the heck
> -- give them credit for ingenuity!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/UWPCE-PythonCert/IntroToPython/issues/132#issuecomment-145738637
> .

## 

Maria Mckinley
Software Developer with Bonus SysAdmin Experience
www.mariakathryn.net
www.linkedin.com/in/mariamckinley

_NOTICE:_ Due to Presidential Executive Orders still not rescinded by
President Obama, the National Security Agency may have read this email
without warning, warrant, or notice, and certainly without probable cause.
They may do this without any judicial or legislative oversight. Click here
to learn more about current US laws and your rights
http://www.aclu.org/national-security/surveillance-privacy.
